version: 2

jobs:
  checkout-cache:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms256m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Download Keystore
          command: echo $RELEASE_KEYSTORE_BASE64 | base64 --decode > build.keystore
      - run:
          name: Create keystore.properies
          command: printf 'releaseKeyAlias=%s\nreleaseKeyPassword=%s\nreleaseKeyStore=%s\nreleaseStorePassword=%s\n'
            $RELEASE_KEY_ALIAS $RELEASE_KEY_PASSWORD build.keystore $RELEASE_STORE_PASSWORD
            > keystore.properties
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies --no-daemon -Pkotlin.incremental=false --max-workers=2 --stacktrace
      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.gradle
            - ~/.bundle
            - ~/project/keystore.properties
            - ~/project/build.keystore

  test-lint:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms256m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Run Lint Test
          command: ./gradlew pmd ktlintCheck --no-daemon -Pkotlin.incremental=false --max-workers=2 --stacktrace

  test-unit-test:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms256m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Run Unit Test
          command: ./gradlew test --no-daemon -Pkotlin.incremental=false --max-workers=2 --stacktrace
      - store_test_results:
          path: updaterengine/build/reports/tests/
          destination: updaterengine/build/reports/tests/
      - store_test_results:
          path: apkupdater/build/reports/tests/
          destination: apkupdater/build/reports/tests/
      - store_test_results:
          path: privilegedinstaller/build/reports/tests/
          destination: privilegedinstaller/build/reports/tests/

  test-proguard:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms256m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Test ProGuard
          command: ./gradlew assembleRelease --no-daemon -Pkotlin.incremental=false --max-workers=2 --stacktrace
      - store_artifacts:
          path: apkupdater/build/outputs/mapping/
          destination: apkupdater/build/outputs/mapping/
      - store_artifacts:
          path: privilegedinstaller/build/outputs/mapping/
          destination: privilegedinstaller/build/outputs/mapping/

  build-updaterengine-debug:
    working_directory: ~/ApkUpdater
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms256m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Build Updater Engine Library (Debug)
          command: ./gradlew :updaterengine:assembleDebug --no-daemon -Pkotlin.incremental=false --max-workers=2 --stacktrace
      - store_artifacts:
          path: updaterengine/build/outputs/aar/
          destination: updaterengine/build/outputs/aar/

  build-updater-debug:
    working_directory: ~/ApkUpdater
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms256m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Build APK Updater (Debug)
          command: ./gradlew :apkupdater:assembleDebug --no-daemon -Pkotlin.incremental=false --max-workers=2 --stacktrace
      - store_artifacts:
          path: apkupdater/build/outputs/apk/
          destination: apkupdater/build/outputs/apk/

  build-privilegedinstaller-debug:
    working_directory: ~/ApkUpdater
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms256m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Build Privileged Installer (Debug)
          command: ./gradlew :privilegedinstaller:assembleDebug --no-daemon -Pkotlin.incremental=false --max-workers=2 --stacktrace
      - store_artifacts:
          path: privilegedinstaller/build/outputs/apk/
          destination: privilegedinstaller/build/outputs/apk/

  deploy-all-releases:
    working_directory: ~/ApkUpdater
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms256m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Build APK Updater (Release)
          command: ./gradlew :updaterengine:assembleRelease :apkupdater:assembleStaging :apkupdater:assembleRelease :privilegedinstaller:assembleStaging :privilegedinstaller:assembleRelease --no-daemon -Pkotlin.incremental=false --max-workers=2 --stacktrace
      - run:
          name: Install FastLane
          command: |
            gem update bundler
            bundle install
      - run:
          name: Release to Github
          command: fastlane releaseGithub
      - store_artifacts:
          path: updaterengine/build/outputs/aar/
          destination: updaterengine/build/outputs/aar/
      - store_artifacts:
          path: apkupdater/build/outputs/apk/
          destination: apkupdater/build/outputs/apk/
      - store_artifacts:
          path: privilegedinstaller/build/outputs/apk/
          destination: privilegedinstaller/build/outputs/apk/

workflows:
  version: 2
  robot:
    jobs:
      - checkout-cache
      - test-lint:
          requires:
            - checkout-cache
      - test-unit-test:
          requires:
            - checkout-cache
      - test-proguard:
          requires:
            - checkout-cache
      - build-updaterengine-debug:
          requires:
            - test-lint
            - test-unit-test
            - test-proguard
      - build-updater-debug:
          requires:
            - build-updaterengine-debug
      - build-privilegedinstaller-debug:
          requires:
            - test-lint
            - test-unit-test
            - test-proguard
      - deploy-all-releases:
          filters:
            branches:
              only: master